project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "CLIP-ASTERIE"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd

format:
  html:
    theme: litera
    toc: true

lang: fr