---
title: "TD 4: Exercice sur le changement de bases"
---

\pagestyle{fancy} 

# Exercice 1 - Arme à l'ancienne
L’une des armes utilisée au Moyen-âge pour envoyer des charges lourdes contre les murailles était ce que l’on appelle “un trébuchet”. Il est composé d’une poutre $AB$ à laquelle est fixée un contrepoids en $A$. 
En $B$ est attachée une corde au bout de laquelle une poche contient le projectile $M$.

Soit $R(O,x,y,z)$ le repère lié au sol et $R_B(B,x_1,y_1,z_1)$ le repère lié à la poutre. 
Le mouvement a lieu dans le plan $(Oxy)$. 
La base polaire $(\vec u_r, \vec u_\varphi)$ est liée à $RB$. On donne $OB = a$ et $BM = b$.



:::: {layout="[ 70, 30 ]"}
::: {#first-column}

## Partie A
3. Appliquer le PFD sur le système. En déduire l’équation différentielle du mouvement de $M$.
4. Résoudre l'équation différentielle du mouvement de $M$. Comment se comporte le bloc $M$ dans le temps?
5. A partir de quel instant $t_1$ les oscillations du système restent-t-elles dans une fourchette de $1cm$ autour du point $O$?


